### ISSUE TITLE
"undefined" ip when running hot reloading on emulator

### ISSUE THREAD

**Issue by Egnus** [syonip/svelte-cordova#1]
This line does not work in my MacOs since I have several internet adapters for many features.
https://github.com/syonip/svelte-cordova/blob/a6ab1a9d5e9a739e86a4a6348cc4ee6e8bae7ffa/before-prepare.js#L26

I recommend you to change that line for this instead to avoid "undefined"

`let ip = interfaces.filter(x => x[0].family == 'IPv4' && x[0].address.includes('192.168'))[0].filter(x => x.family == 'IPv4').map(x => x.address)[0]`

I can do the Pull request if you need so.

**Comment by syonip** [comment]
Thanks for opening this issue @Egnus,
I think that including the `192.168` filter would cause problems for some routers that use other address prefixes (mine uses `10.0`).
Can you add the line `console.dir(interfaces)` and show the output, so we can try to find the correct interface generically?

**Comment by Egnus** [comment]
Hi again,
sorry for the late response, i was away.
Certainly my patch gave me other errors afterwards. In this case, "Cannot read property 'filter' of undefined"
Easy to fix perhaps but you are right and it would be better to get a better approach from your perspective, this is the log of the interfaces i have just before that.

```
interfaces = [
  [
    {
      address: '************************',
      netmask: 'ffff:ffff:ffff:ffff::',
      family: 'IPv6',
      mac: '************************',
      internal: false,
      cidr: '************************',
      scopeid: 8
    }
  ],
  [
    {
      address: '************************',
      netmask: 'ffff:ffff:ffff:ffff::',
      family: 'IPv6',
      mac: '************************',
      internal: false,
      cidr: '************************',
      scopeid: 10
    },
    {
      address: '192.168.1.15',
      netmask: '255.255.255.0',
      family: 'IPv4',
      mac: '************************',
      internal: false,
      cidr: '192.168.1.15/24'
    }
  ],
  [
    {
      address: '************************',
      netmask: 'ffff:ffff:ffff:ffff::',
      family: 'IPv6',
      mac: '************************',
      internal: false,
      cidr: '************************',
      scopeid: 12
    }
  ],
  [
    {
      address: '************************',
      netmask: 'ffff:ffff:ffff:ffff::',
      family: 'IPv6',
      mac: '00:00:00:00:00:00',
      internal: false,
      cidr: '************************',
      scopeid: 18
    }
  ]
]
```
I only have at the moment a single IPv4 connection but sometimes i will have 2 plus one external, any other alternative for this line?

**Comment by Egnus** [comment]
I simplified the array by using `Array.prototipe.flat`

The snipped i use now in my project is this:
`let ip = interfaces.flat(5).filter(x => x.family == 'IPv4' && x.address.includes('192.168')).map(x => x.address);`

I know that not all LAN connections in the planet are driven by "192.168" but honestly i don't know what other alternatives i could use to fit all the cases.

In any case, the "Flat" is something you could consider

**Comment by syonip** [comment]
Hi again @Egnus,
I implemented your suggestion of using flat, and added some tests to prevent regressions.
It seems to work well for both your setting and mine.
I'll publish an updated package to npm shortly.
Tell me if it works.

**Comment by syonip** [comment]
version 1.0.6 published to npm
