### ISSUE TITLE
Error on cordova-run-android

### ISSUE THREAD

**Issue by paradis-A** [syonip/svelte-cordova#3]
Heres the error: 
`[2020-07-13 02:40:17] waiting for changes...
interfaces.flat is not a function
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! svelte-app@1.0.0 cordova-run-android: `cd src-cordova && cordova run android`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the svelte-app@1.0.0 cordova-run-android script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\MIS\AppData\Roaming\npm-cache\_logs\2020-07-12T18_40_18_311Z-debug.log
ERROR: "cordova-run-android" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! svelte-app@1.0.0 dev-android: `cross-env CORDOVA_PLATFORM=android run-p serve:cordova autobuild cordova-run-android`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the svelte-app@1.0.0 dev-android script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\MIS\AppData\Roaming\npm-cache\_logs\2020-07-12T18_40_18_579Z-debug.log
PS C:\cordova\cmfoods\customerapp>`

when i tried to run the command 'npm run cordova-run-android', it works on my device but it prompts error on the device again
here the message 
`net::ERR_FILE_NOT_FOUND (file:///android_asset/www/index.html)`

**Comment by syonip** [comment]
Hi @clarenceeda ,
Seems like the script is crashing trying to find the network interface on your dev machine.
Can you provide the output of `os.networkInterfaces()` on your dev machine?
