### ISSUE TITLE
device cannot connect to ipaddress laptop(dev server)

### ISSUE THREAD

**Issue by beebase** [syonip/svelte-cordova#7]
executing npm run dev-android on my laptop is OK. I can connect to dev server from a browser on my laptop.
However on my adroid device a get a connection error.
(btw:  laptop ipaddress received from router is different from the ip address the dev server is running on.)

Are there any network settings I should check first?
(I tried disabling firewall on my laptop)

**Comment by syonip** [comment]
Hi @beebase ,
You can try to debug this by adding a breakpoint or console.log to where the ip is retrieved, as described in this issue: https://github.com/syonip/svelte-cordova/issues/4

**Comment by beebase** [comment]
I ended up hardcoding my laptop's ip-address which works fine for me.
Thanks for building this package. 😃  Looking forward to finally start developing directly to my phone.


**node-modules/svelte-cordova/before-prepare.js**
```
[line 89]
const publicFolder = '../public'
//const ip = process.env.SERVER_IP ? process.env.SERVER_IP : ipLogic.getIP(networkInterfaces)
const ip = '192.168.178.60'
const url = production ? 'index.html' : `http://${ip}:5000`
```

**Comment by syonip** [comment]
Happy to hear, good luck :)
